name: "i18next-google-sheet-action"
description: "Actions to automate translations"
inputs:
  path:
    description: "locales directory path"
    required: true
    default: "locales/"
  range:
    description: "spreadsheet range"
    required: true
    default: "시트1"
  spreadsheet-id:
    description: "spreadsheet id"
    required: true
outputs:
  stats:
    description: "i18next sync result"
  has-changed:
    description: "check if the google spreadsheet has changed"
runs:
  using: "node16"
  main: "dist/index.mjs"
